### ISSUE TITLE
Shield Check that Form ID is not same as Task ID

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-backend-test#6] opened 2020-06-16 14:09 UTC
Ran into an issues on production that caused an error on this line.  We had a bpmn document where a Form had the same id as the Task.  Nothing caught it, and the error was hard to track down.  Would be good to validate that all ids are unique and return an error if that isn't he case.
STG-24

https://github.com/sartography/SpiffWorkflow/blob/master/SpiffWorkflow/bpmn/parser/TaskParser.py#L207

**Comment by danfunk** [comment] 2020-11-23 15:50
If we catch this in SpiffWorkflow, during parsing, and raise a WorkflowException, that should naturally report the error back up, and get caught by the validation script. 

OR - This is likely because some part of the parser is NOT namespace aware - particularly the part that is looking at task ids. And that this shouldn't even be an error.

**Comment by cullerton** [comment] 2020-12-01 17:05
I cannot reproduce this issue. It is possible the problem was fixed while working on a different issue. I am closing this ticket.

**Closed as completed** 2020-12-01 17:05 UTC
